'\" t
.\"     Title: flashproxy-reg-email
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/10/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "FLASHPROXY\-REG\-EMAIL" "1" "10/10/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
flashproxy-reg-email \- Register with a facilitator using the email method
.SH "SYNOPSIS"
.sp
\fBflashproxy\-reg\-email\fR [\fIOPTIONS\fR] [\fIREMOTE\fR][:\fIPORT\fR]
.SH "DESCRIPTION"
.sp
Register with a flash proxy facilitator through email\&. Makes a STARTTLS connection to an SMTP server and sends mail with a client IP address to a designated address\&. By default the remote address registered is ":9000" (the external IP address is guessed based on the SMTP server\(cqs response)\&.
.sp
Using an SMTP server or email address other than the defaults will not work unless you have made special arrangements to connect them to a facilitator\&.
.sp
The email address is not polled continually\&. After running the program, it may take up to a minute for the registration to be recognized\&.
.sp
This program requires the M2Crypto library for Python\&.
.SH "OPTIONS"
.PP
\fB\-4\fR
.RS 4
Name lookups use only IPv4\&.
.RE
.PP
\fB\-6\fR
.RS 4
Name lookups use only IPv6\&.
.RE
.PP
\fB\-d\fR, \fB\-\-debug\fR
.RS 4
Enable debugging output (Python smtplib messages)\&.
.RE
.PP
\fB\-\-disable\-pin\fR
.RS 4
Don\(cqt check the server\(cqs public key against a list of known pins\&. You can use this if the server\(cqs public key has changed and this program hasn\(cqt been updated yet\&.
.RE
.PP
\fB\-e\fR, \fB\-\-email\fR=\fIADDRESS\fR
.RS 4
Send mail to
\fIADDRESS\fR
(default is "flashproxyreg\&.a@gmail\&.com")\&.
.RE
.PP
\fB\-\-facilitator\-pubkey\fR=\fIFILENAME\fR
.RS 4
Encrypt registrations to the given PEM\-formatted public key (default built\-in)\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display help message and exit\&.
.RE
.PP
\fB\-s\fR, \fB\-\-smtp\fR=\fIHOST\fR[:\fIPORT\fR]
.RS 4
Use the given SMTP server (default is "gmail\-smtp\-in\&.l\&.google\&.com:25")\&.
.RE
.PP
\fB\-\-transport\fR=\fITRANSPORT\fR
.RS 4
Registrations include the fact that you intend to use the given
\fITRANSPORT\fR
(default "websocket")\&.
.RE
.PP
\fB\-\-unsafe\-logging\fR
.RS 4
Don\(cqt scrub IP addresses from logs\&.
.RE
.SH "SEE ALSO"
.sp
\fBhttp://crypto\&.stanford\&.edu/flashproxy/\fR
.sp
\fBhttps://www\&.torproject\&.org/docs/pluggable\-transports\&.html\&.en\fR
.SH "BUGS"
.sp
Please report using \fBhttps://trac\&.torproject\&.org/projects/tor\fR\&.
