#!/bin/sh

# Fakes a Tor pluggable transports server environment.

export TOR_PT_MANAGED_TRANSPORT_VER="1"
export TOR_PT_SERVER_TRANSPORTS="*"
export TOR_PT_SERVER_BINDADDR="websocket-0.0.0.0:0"
export TOR_PT_ORPORT="127.0.0.1:9001"

exec $@
